apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/priya007-bit/ApplicationSet-Demo.git   # change me
    targetRevision: main
    path: services/app-a
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default   # deploy to default namespace
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
